name: flerta_ai
description: "Aplicativo de paquera com IA focado no mercado brasileiro"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Dependências obrigatórias conforme especificação
  supabase_flutter: ^2.0.0
  supabase_auth_ui: ^0.3.0
  dart_openai: ^5.0.0
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_card_swiper: ^7.0.1
  geolocator: ^10.1.0
  
  # Dependências adicionais para UI e funcionalidades
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
  
  # Fonts (commented out until font files are added)
  # fonts:
  #   - family: Nunito
  #     fonts:
  #       - asset: assets/fonts/Nunito-Regular.ttf
  #       - asset: assets/fonts/Nunito-Bold.ttf
  #         weight: 700
